# Generated by Django 4.2.1 on 2023-05-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'category'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'ordering': ['product', 'model', 'shop', 'quantity'], 'verbose_name': 'Информация о товаре', 'verbose_name_plural': 'Информационные листы о товаре'},
        ),
    ]
