# Generated by Django 4.2.5 on 2023-09-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='models',
            field=models.CharField(blank=True, max_length=40, verbose_name='Модель'),
        ),
    ]
