# Generated by Django 4.2.5 on 2023-09-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_order_contact_productinfo_external_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='state',
        ),
    ]
