# Generated by Django 4.2.5 on 2023-09-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_status_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_info',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='backend.productinfo', verbose_name='Информация о заказе'),
        ),
    ]
