# Generated by Django 4.2.5 on 2023-09-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yml_file', models.FileField(upload_to='uploads/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Импорт товаров',
                'verbose_name_plural': 'Импорты товаров',
                'ordering': ('-date_added',),
            },
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('-name',), 'verbose_name': 'Магазин', 'verbose_name_plural': 'Список магазинов'},
        ),
    ]
