# Generated by Django 4.2.5 on 2023-09-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_shopimport_yml_file_shopimport_yml_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopimport',
            name='yml_url',
        ),
        migrations.AddField(
            model_name='shopimport',
            name='yml_file',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
