# Generated by Django 4.2.5 on 2023-10-16 08:33

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_shopimport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='image/user_image/', verbose_name='Аватарка', width_field='width'),
        ),
    ]
