# Generated by Django 4.2.5 on 2023-10-16 08:53

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='image/user_image/', verbose_name='Аватарка'),
        ),
    ]
