# Generated by Django 4.2.5 on 2023-10-17 11:39

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_product_photo_product_photo_ppoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='F:\\Update\\python-final-diplom\\orders\\media\\image\\user_image\\default_image.png', null=True, upload_to='image/user_image/', verbose_name='Аватарка'),
        ),
    ]
