# Generated by Django 4.2.5 on 2023-10-17 11:43

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_ppoi',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='default_image.png', null=True, upload_to='image/user_image/', verbose_name='Аватарка'),
        ),
    ]
