# Generated by Django 4.2.5 on 2023-10-17 11:44

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_user_image_ppoi_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='image/user_image/default_image.png', null=True, upload_to='image/user_image/', verbose_name='Аватарка'),
        ),
    ]
