# Generated by Django 4.2.5 on 2023-10-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_user_image_ppoi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_ppoi',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_ppoi',
        ),
    ]
