# Generated by Django 4.2.5 on 2023-10-17 16:49

import backend.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_remove_product_photo_ppoi_remove_user_image_ppoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='image/user_image/default_product_image.png', help_text='Image max 800x800', null=True, upload_to=backend.models.get_path_image, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='image/user_image/default_image.png', help_text='Image max 600x600', null=True, upload_to=backend.models.get_path_image, verbose_name='Аватарка'),
        ),
    ]
