# Generated by Django 4.2.5 on 2023-10-17 17:19

import backend.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='image/products_image/default_product_image.jpg', help_text='Max image size up to 800x800', null=True, upload_to=backend.models.get_path_image, verbose_name='Фото'),
        ),
    ]
