# Generated by Django 4.2.5 on 2023-10-21 21:58

import backend.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_remove_product_photo_productinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='image/user_image/default_image.png', help_text='Max size image up to 800x800', null=True, upload_to=backend.models.get_path_image, verbose_name='Аватарка'),
        ),
    ]
