# примеры API-запросов

@baseUrl = http://localhost:8000/

# создание продукта
POST {{baseUrl}}partner/update
Authorization: Token ebb74b65b6b3682e4df538ba3d2d5ef4609e771e
Content-Type: application/json

{"url": "https://drive.google.com/uc?export=download&confirm=no_antivirus&id=1K30Oeujse-05WCEGEFZC6oOX4Q_kACPy"}

###


###

