openapi: 3.0.3
info:
  title: Shop Service API
  version: 1.0.0
  description: 'A service to make the communication between sellers and buyers easier.
    For more information, visit https://github.com/alina-vorontsova/python-final-diplom/blob/master/README.md '
paths:
  /basket/:
    patch:
      operationId: basket_partial_update
      description: Заполнить адрес при оформлении заказа на стадии 'в корзине'.
      tags:
      - basket
      security:
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /categories/:
    get:
      operationId: categories_list
      description: Просмотр всех категорий товаров и сортировка по параметру 'магазины'.
      parameters:
      - in: query
        name: shops
        schema:
          type: array
          items:
            type: integer
        explode: true
        style: form
      tags:
      - categories
      security:
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
          description: ''
  /categories/{id}/:
    get:
      operationId: categories_retrieve
      description: Просмотр всех категорий товаров и сортировка по параметру 'магазины'.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
          maximum: 2147483647
          minimum: 0
        description: A unique value identifying this Категория.
        required: true
      tags:
      - categories
      security:
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
          description: ''
  /get_contact/:
    post:
      operationId: get_contact_create
      description: Внести в базу данных контактную информацию определённого пользователя.
      tags:
      - get_contact
      security:
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /login/:
    post:
      operationId: login_create
      description: Войти в систему от лица определённого пользователя.
      tags:
      - login
      security:
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /new_order/:
    post:
      operationId: new_order_create
      description: Создать новый заказ.
      tags:
      - new_order
      security:
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /order_confirmation/:
    post:
      operationId: order_confirmation_create
      description: Получить потверждение заказа от пользователя и отправить эл. письмо
        с подтверждением заказа.
      tags:
      - order_confirmation
      security:
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /orders/:
    get:
      operationId: orders_list
      description: Просмотр общей информации о всех заказах и подробной информации
        об одном заказе.
      tags:
      - orders
      security:
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
          description: ''
  /orders/{id}/:
    get:
      operationId: orders_retrieve
      description: Просмотр общей информации о всех заказах и подробной информации
        об одном заказе.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Заказ.
        required: true
      tags:
      - orders
      security:
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderInfo'
          description: ''
  /products/:
    get:
      operationId: products_list
      description: Просмотр всех товаров и сортировка по параметру 'категория'.
      parameters:
      - in: query
        name: category
        schema:
          type: integer
          maximum: 2147483647
          minimum: 0
      tags:
      - products
      security:
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          description: ''
  /products/{id}/:
    get:
      operationId: products_retrieve
      description: Просмотр всех товаров и сортировка по параметру 'категория'.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Товар.
        required: true
      tags:
      - products
      security:
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
  /register/:
    post:
      operationId: register_create
      description: |-
        Создать в базе данных запись с информацией о новом пользователе.
        Отправить сообщение с подтверждением о регистрации.
      tags:
      - register
      security:
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /shops/:
    get:
      operationId: shops_list
      description: Просмотр всех магазинов и сортировка по параметру 'статус'.
      parameters:
      - in: query
        name: state
        schema:
          type: boolean
      tags:
      - shops
      security:
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Shop'
          description: ''
  /shops/{id}/:
    get:
      operationId: shops_retrieve
      description: Просмотр всех магазинов и сортировка по параметру 'статус'.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Магазин.
        required: true
      tags:
      - shops
      security:
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shop'
          description: ''
  /update/{file_name}/:
    post:
      operationId: update_create
      description: |-
        Загрузить в базу данных информацию о магазине, категориях товаров, товарах, характеристиках.

        Ключевые аргументы:
        file_name -- название файла относительно файла manage.py, формат .yaml.
      parameters:
      - in: path
        name: file_name
        schema:
          type: string
        required: true
      tags:
      - update
      security:
      - basicAuth: []
      responses:
        '200':
          description: No response body
components:
  schemas:
    Category:
      type: object
      description: Работа с категориями товаров.
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Название
          maxLength: 40
        shops:
          type: array
          items:
            type: string
      required:
      - id
      - name
      - shops
    Contact:
      type: object
      description: Работа с контактами пользователей.
      properties:
        city:
          type: string
          title: Город
          maxLength: 50
        street:
          type: string
          title: Улица
          maxLength: 100
        house:
          type: string
          nullable: true
          title: Дом
          maxLength: 15
        building:
          type: string
          nullable: true
          title: Строение
          maxLength: 15
        structure:
          type: string
          nullable: true
          title: Корпус
          maxLength: 15
        apartment:
          type: string
          nullable: true
          title: Квартира
          maxLength: 15
        phone:
          type: string
          title: Телефон
          maxLength: 20
      required:
      - city
      - phone
      - street
    DetailedOrderItem:
      type: object
      description: Работа с подробной информацией о позициях в заказе.
      properties:
        order:
          type: integer
          nullable: true
          title: Заказ
        product_info:
          allOf:
          - $ref: '#/components/schemas/ProductInfo'
          readOnly: true
        quantity:
          type: integer
          maximum: 2147483647
          minimum: 0
          title: Количество
      required:
      - product_info
      - quantity
    Order:
      type: object
      description: Работа с общей информацией о заказах.
      properties:
        id:
          type: integer
          readOnly: true
        user:
          type: integer
          writeOnly: true
          nullable: true
          title: Пользователь
        dt:
          type: string
          format: date-time
          readOnly: true
          title: Дата и время создания
        state:
          allOf:
          - $ref: '#/components/schemas/StateEnum'
          title: Статус
        total_sum:
          type: integer
        contact:
          allOf:
          - $ref: '#/components/schemas/Contact'
          readOnly: true
      required:
      - contact
      - dt
      - id
      - state
      - total_sum
    OrderInfo:
      type: object
      description: Работа с подробной информацией о заказах и позициях в них.
      properties:
        dt:
          type: string
          format: date-time
          readOnly: true
          title: Дата и время создания
        state:
          allOf:
          - $ref: '#/components/schemas/StateEnum'
          title: Статус
        user:
          allOf:
          - $ref: '#/components/schemas/User'
          readOnly: true
        contact:
          allOf:
          - $ref: '#/components/schemas/Contact'
          readOnly: true
        order_items:
          type: array
          items:
            $ref: '#/components/schemas/DetailedOrderItem'
          readOnly: true
        total_sum:
          type: integer
      required:
      - contact
      - dt
      - order_items
      - state
      - total_sum
      - user
    Product:
      type: object
      description: Работа с общей информацией о товарах.
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Название
          maxLength: 100
        category:
          type: string
          readOnly: true
      required:
      - category
      - id
      - name
    ProductInfo:
      type: object
      description: Работа с подробной информацией о товарах.
      properties:
        id:
          type: integer
          readOnly: true
        external_id:
          type: integer
          maximum: 2147483647
          minimum: 0
          title: Внешний Id
        product:
          allOf:
          - $ref: '#/components/schemas/Product'
          readOnly: true
        model:
          type: string
          title: Модель
          maxLength: 100
        shop:
          type: integer
          nullable: true
          title: Магазин
        quantity:
          type: integer
          maximum: 2147483647
          minimum: 0
          title: Количество
        price:
          type: integer
          maximum: 2147483647
          minimum: 0
          title: Цена
        price_rrc:
          type: integer
          maximum: 2147483647
          minimum: 0
          title: Рекомендуемая розничная цена
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/ProductParameter'
          readOnly: true
      required:
      - external_id
      - id
      - model
      - parameters
      - price
      - price_rrc
      - product
      - quantity
    ProductParameter:
      type: object
      description: Работа с параметрами товаров.
      properties:
        id:
          type: integer
          readOnly: true
        parameter:
          type: string
          readOnly: true
        value:
          type: string
          nullable: true
          title: Значение
          maxLength: 40
      required:
      - id
      - parameter
    Shop:
      type: object
      description: Работа с магазинами.
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Название
          maxLength: 40
        state:
          type: boolean
          title: Статус
      required:
      - id
      - name
    StateEnum:
      enum:
      - basket
      - newНовый
      - confirmed
      - assembled
      - sent
      - delivered
      - canceled
      type: string
      description: |-
        * `basket` - Статус корзины
        * `newНовый` - New
        * `confirmed` - Подтвержден
        * `assembled` - Собран
        * `sent` - Отправлен
        * `delivered` - Доставлен
        * `canceled` - Отменен
    User:
      type: object
      description: Работа с пользователями.
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          title: Эл. почта
          maxLength: 254
        full_name:
          type: string
          nullable: true
          title: Фамилия, имя, отчество
          maxLength: 100
      required:
      - email
      - id
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
