# Generated by Django 3.2.9 on 2021-12-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='test',
        ),
    ]
