# Generated by Django 3.2.9 on 2022-01-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('client', 'Клиент'), ('supplier', 'Поставщик')], default='client', max_length=8, verbose_name='Тип пользователя'),
        ),
    ]
