# Generated by Django 3.2.9 on 2022-01-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20220102_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('C', 'Клиент'), ('S', 'Поставщик')], default='client', max_length=8, verbose_name='Тип пользователя'),
        ),
    ]
