# Generated by Django 3.2.9 on 2022-01-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='shop_orders', through='orders.OrderContent', to='products.ProductInfo', verbose_name='Список продуктов'),
        ),
    ]
