# Generated by Django 3.2.9 on 2022-01-04 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_shop_user'),
        ('orders', '0004_auto_20220104_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shops.shop', verbose_name='Магазин'),
        ),
    ]
