# Generated by Django 3.2.9 on 2021-12-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['-name'], 'verbose_name': 'Параметра', 'verbose_name_plural': 'Список параметров'},
        ),
        migrations.AlterModelOptions(
            name='parametervalue',
            options={'verbose_name': 'Продукт и параметр', 'verbose_name_plural': 'Список продуктов и параметров'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
