# Generated by Django 3.2.9 on 2021-12-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211212_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя'),
        ),
    ]
