# Generated by Django 3.2.9 on 2022-01-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220109_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='internal_product_id',
            field=models.PositiveIntegerField(default='1', verbose_name='Внутренний идентификатор категории'),
            preserve_default=False,
        ),
    ]
