# Generated by Django 3.2.9 on 2022-01-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productinfo_product_alter_productinfo_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Список продуктов'},
        ),
    ]
