# Generated by Django 3.2.9 on 2021-12-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Список категорий',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Категория')),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Магазин и категория',
                'verbose_name_plural': 'Список магазинов и категорий',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='shops',
            field=models.ManyToManyField(blank=True, related_name='categories', through='categories.ShopCategory', to='shops.Shop', verbose_name='Список магазинов'),
        ),
        migrations.AddConstraint(
            model_name='shopcategory',
            constraint=models.UniqueConstraint(fields=('shop', 'category'), name='unique_shop_category'),
        ),
    ]
