# Generated by Django 3.2.9 on 2021-12-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopcategory',
            options={'verbose_name': 'Магазин и категория', 'verbose_name_plural': 'Список магазинов и категорий'},
        ),
    ]
