# Generated by Django 3.2.9 on 2022-01-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcategory',
            name='shop',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='category',
            name='shops',
            field=models.ManyToManyField(blank=True, related_name='categories', through='categories.ShopCategory', to='shops.Shop', verbose_name='Список магазинов'),
        ),
        migrations.AddConstraint(
            model_name='shopcategory',
            constraint=models.UniqueConstraint(fields=('shop', 'category'), name='unique_shop_category'),
        ),
    ]
