# Generated by Django 3.2.9 on 2022-01-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcategory',
            name='internal_category_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Внутренний идентификатор категории'),
            preserve_default=False,
        ),
    ]
