"""empty message

Revision ID: 3ff784677c4b
Revises: e04acb2fec73
Create Date: 2021-03-11 13:36:31.272625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3ff784677c4b"
down_revision = "e04acb2fec73"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shop", sa.Column("file_upload_datetime", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shop", "file_upload_datetime")
    # ### end Alembic commands ###
