"""empty message

Revision ID: 6f646c5149ac
Revises: 5b0f4e373099
Create Date: 2021-02-22 21:56:08.959052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6f646c5149ac"
down_revision = "5b0f4e373099"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_token_key", "user", type_="unique")
    op.drop_column("user", "expires_at")
    op.drop_column("user", "token")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("token", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column("user", sa.Column("expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_unique_constraint("user_token_key", "user", ["token"])
    # ### end Alembic commands ###
