"""empty message

Revision ID: 7683e0ecfc9e
Revises: a8614ead5e50
Create Date: 2021-03-31 13:21:57.487203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7683e0ecfc9e"
down_revision = "a8614ead5e50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=True),
        sa.Column("zip_code", sa.String(length=6), nullable=True),
        sa.Column("city", sa.String(length=50), nullable=True),
        sa.Column("street", sa.String(length=100), nullable=True),
        sa.Column("house", sa.String(length=15), nullable=True),
        sa.Column("structure", sa.String(length=15), nullable=True),
        sa.Column("building", sa.String(length=15), nullable=True),
        sa.Column("apartment", sa.String(length=15), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["user"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "cart",
                "new",
                "confirmed",
                "assembled",
                "sent",
                "delivered",
                "canceled",
                name="orderstatechoices",
            ),
            nullable=False,
        ),
        sa.Column("contact", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact"],
            ["contact.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "x_order_item",
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("product", sa.Integer(), nullable=False),
        sa.Column("shop", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order"],
            ["order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shop"],
            ["shop.id"],
        ),
        sa.PrimaryKeyConstraint("order", "product", "shop"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("x_order_item")
    op.drop_table("order")
    op.drop_table("contact")
    # ### end Alembic commands ###
