"""empty message

Revision ID: 79b64d436405
Revises: 3ff784677c4b
Create Date: 2021-03-11 14:44:40.344590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "79b64d436405"
down_revision = "3ff784677c4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("shop", "user_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("shop", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
