"""empty message

Revision ID: a8614ead5e50
Revises: fd3422951de8
Create Date: 2021-03-30 12:10:44.547062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a8614ead5e50"
down_revision = "fd3422951de8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_info", sa.Column("slug", sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_info", "slug")
    # ### end Alembic commands ###
