"""empty message

Revision ID: e04acb2fec73
Revises: 2c539b07971c
Create Date: 2021-03-11 13:30:52.348499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e04acb2fec73"
down_revision = "2c539b07971c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shop", sa.Column("title", sa.String(length=255), nullable=False))
    op.drop_constraint("shop_name_key", "shop", type_="unique")
    op.create_unique_constraint(None, "shop", ["title"])
    op.drop_column("shop", "name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shop", sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, "shop", type_="unique")
    op.create_unique_constraint("shop_name_key", "shop", ["name"])
    op.drop_column("shop", "title")
    # ### end Alembic commands ###
