# Generated by Django 4.1.7 on 2023-03-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this user email is verified.', verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
