# Generated by Django 3.2.9 on 2021-12-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='url',
        ),
    ]
