# Generated by Django 3.2.9 on 2021-12-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_remove_shop_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
