# Generated by Django 3.2.9 on 2022-01-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Статус заказов'),
        ),
    ]
